-- Animations: macOS-like, snappy, controlled motion
hl.curve("macSpring", { type = "spring", mass = 1, stiffness = 450, dampening = 45 })
hl.curve("macSoftSpring", { type = "spring", mass = 1, stiffness = 350, dampening = 38 })
hl.curve("snappyOut", { type = "bezier", points = { { 0.16, 1 }, { 0.3, 1 } } })
hl.curve("smoothFocus", { type = "bezier", points = { { 0.25, 1 }, { 0.5, 1 } } })
hl.curve("default", { type = "bezier", points = { { 0, 1 }, { 0, 1 } } })

hl.animation({ leaf = "windows", enabled = true, speed = 1.5, spring = "macSpring" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 1.5, spring = "macSpring", style = "popin 85%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.4, bezier = "snappyOut", style = "popin 88%" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 1.2, spring = "macSpring" })
hl.animation({ leaf = "border", enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 2.5, bezier = "snappyOut" })
hl.animation({ leaf = "fadeSwitch", enabled = true, speed = 6, bezier = "smoothFocus" })
hl.animation({ leaf = "fadeDim", enabled = true, speed = 6, bezier = "smoothFocus" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.5, spring = "macSoftSpring", style = "slidefade 18%" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 3.2, bezier = "snappyOut", style = "popin 90%" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 2.2, bezier = "snappyOut", style = "fade" })
