#!/usr/bin/env bash
# Regenerate the README backup package list from packages/desktop-core.txt.
# Rewrites everything between the pkglist markers. Run after editing the manifest.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

BLOCK="$(grep -hvE '^\s*(#|$)' packages/desktop-core.txt | tr '\n' ' ' | fold -s -w 70 | sed 's/ $/ \\/')"
{
  echo '<!-- pkglist:begin (generated by scripts/sync-readme-pkglist.sh) -->'
  echo '```bash'
  printf 'paru -S --needed %s\n' "$BLOCK" | sed '$ s/ \\$//'
  echo '```'
  echo '<!-- pkglist:end -->'
} > /tmp/pkglist-block.md

awk '/<!-- pkglist:begin/{while((getline l < "/tmp/pkglist-block.md")>0) print l; skip=1} /<!-- pkglist:end/{skip=0; next} !skip' README.md > /tmp/README.md.new
mv /tmp/README.md.new README.md
echo "README package list synced from packages/desktop-core.txt"
